<?php

namespace App\Application\Sonata\UserBundle;

use App\Application\Sonata\UserBundle\DependencyInjection\ApplicationSonataUserExtension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://symfony.com/doc/current/book/bundles.html
 */
class ApplicationSonataUserBundle extends Bundle
{
    public function getContainerExtension()
    {
        return new ApplicationSonataUserExtension();
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'SonataUserBundle';
    }

    public function build(ContainerBuilder $container)
    {
        $extension = $container->getExtension('security');
        $extension->addSecurityListenerFactory(new \App\Application\Sonata\UserBundle\Security\Factory\CustomFormLoginFactory());
    }
}
