fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    # user_class: App\Entity\User
    user_class:     App\Application\Sonata\UserBundle\Entity\User

    from_email:
        address: "%mailer_sender_email%"
        sender_name: "%mailer_sender_name%"
    group:
        # group_class:   FOS\UserBundle\Entity\Group
        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    registration:
        confirmation:
            enabled:  true
#            template: ApplicationUserBundle:Registration:email.html.twig

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: Core\UserBundle\Mailer\Mailer
